name: Lighthouse Performance Audit

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    name: Lighthouse Audit
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g @lhci/cli@0.12.x
          npm install -g http-server

      - name: Start local server
        run: |
          cd Nithilan
          http-server -p 8080 -s &
          sleep 5
        
      - name: Run Lighthouse CI
        run: |
          lhci autorun --upload.target=temporary-public-storage --collect.url=http://localhost:8080
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Run Lighthouse audit manually
        run: |
          # Install Lighthouse
          npm install -g lighthouse
          
          # Run Lighthouse on main pages
          lighthouse http://localhost:8080 --output=json --output-path=./lighthouse-home.json --chrome-flags="--headless --no-sandbox"
          lighthouse http://localhost:8080/contact.html --output=json --output-path=./lighthouse-contact.json --chrome-flags="--headless --no-sandbox" || true
          
          # Generate summary
          echo "## Lighthouse Performance Report" > lighthouse-summary.md
          echo "Generated on: $(date)" >> lighthouse-summary.md
          echo "" >> lighthouse-summary.md
          
          # Extract scores from JSON (basic parsing)
          if [ -f lighthouse-home.json ]; then
            echo "### Home Page Results:" >> lighthouse-summary.md
            echo "- Performance: $(cat lighthouse-home.json | grep -o '"performance":[0-9.]*' | cut -d: -f2 | head -1)" >> lighthouse-summary.md
            echo "- Accessibility: $(cat lighthouse-home.json | grep -o '"accessibility":[0-9.]*' | cut -d: -f2 | head -1)" >> lighthouse-summary.md
            echo "- Best Practices: $(cat lighthouse-home.json | grep -o '"best-practices":[0-9.]*' | cut -d: -f2 | head -1)" >> lighthouse-summary.md
            echo "- SEO: $(cat lighthouse-home.json | grep -o '"seo":[0-9.]*' | cut -d: -f2 | head -1)" >> lighthouse-summary.md
          fi

      - name: Upload Lighthouse reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: |
            lighthouse-*.json
            lighthouse-summary.md
